//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATABASE.MODELS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tour_Gia
    {
        public int MaTourGia { get; set; }
        public int MaTour { get; set; }
        public System.DateTime TGBD { get; set; }
        public System.DateTime TGKT { get; set; }
        public int Gia { get; set; }
        public bool TrangThai { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
